### ISSUE TITLE
TODO: Exosuit Armor Upgrades

### ISSUE THREAD

**Issue by sky0-1** [sky0-1/Planetary#2]
- [X] Night Vision - helmet
- [X] Gravity Enhancer - feet
- [ ] Speed buff - legs
- [ ] Jetpack - chest
- [ ] Battery cells - all
- [ ] Extra armor plating - all
